### ISSUE TITLE
Unresolved reference to `muhat` (`combo_fixes` branch)

### ISSUE THREAD

**Issue by jackaraz** [SModelS/smodels#18]
`lmax` function returns `self.likelihood(muhat * nsig, marginalize=marginalize, nll=nll)` but `muhat` is not defined in the function. This needs to be modified to either `muhat_` or `self.muhat`.

https://github.com/SModelS/smodels/blob/1f3981b33b88fd8eb02152aa1b5cf70897dfd191/smodels/tools/simplifiedLikelihoods.py#L915-L918

**Comment by WolfgangWaltenberger** [comment]
fixed with 519576ffab098af83700db6696ea3173afdfd3f1
