### ISSUE TITLE
RAM overflows when running SmodelS

### ISSUE THREAD

**Issue by mmrowietz** [SModelS/smodels#2]
SmodelS regularly uses up all the RAM of my machine when running on a slha, resulting in a crash.

**Comment by WolfgangWaltenberger** [comment]
As a quick workaround, have you tried setting caching.Cache.n_stored to e.g. 100?
Does that solve the issue?

**Comment by mmrowietz** [comment]
I tried reducing it from 1000 to 400. That didn't seem to help at all. Should I try to go to 100 or lower?

**Comment by WolfgangWaltenberger** [comment]
Would you please attach the slha file and the ini files to your problem report?

**Comment by mmrowietz** [comment]
I should probably mention that I run over a couple of thousand slha files, so maybe that is where the problem lies.

[crashing.zip](https://github.com/SModelS/smodels/files/1245564/crashing.zip)

**Comment by WolfgangWaltenberger** [comment]
![mprof5000_7](https://user-images.githubusercontent.com/5710451/36808923-c92bfc3c-1cc6-11e8-99c0-49647bfbc8cb.png)

Okay, I made a few small improvements in v1.1.2, and profiled a round over 300 files and 8 cores, attached is the plot. We might have to dig into this further, investigate where this spike comes from, but for now I leave it as it is.
