### ISSUE TITLE
Please test pyhf v0.7.0 release candidates

### ISSUE THREAD

**Issue by matthewfeickert** [SModelS/smodels#22]
Hi. :wave: As you're a user of `pyhf`

https://github.com/SModelS/smodels/blob/d946c87ea64655ccabab0ee592816f8a575b13ec/smodels/share/requirements.txt#L7

please test the [`pyhf` `v0.7.0` release candidates](https://github.com/scikit-hep/pyhf/releases/tag/v0.7.0rc4) to see if you will be affected by any of the API changes.

```
python -m pip install --upgrade --pre pyhf
```

If you haven't yet, please also consider joining the [pyhf-announcements mailing list](https://groups.google.com/group/pyhf-announcements/subscribe).

This Issue is meant to be helpful to avoid unexpected breaks of your code, but if you find this intrusive or annoying please let us know and we won't bother you again.

**Comment by WolfgangWaltenberger** [comment]
Tried. We saw no change from 0.6.x, neither numerically nor technically, API-wise. Green light from our side. Godspeed! ;)

**Comment by matthewfeickert** [comment]
Fantastic! Thanks so much. Also apologies for the very long gap in releases &mdash; we'll work to make sure this doesn't happen again.
