### ISSUE TITLE
make FC or FCC to specify the Fortran compiler

### ISSUE THREAD

**Issue by tueda** [SModelS/smodels#23]
[The manual says](https://smodels.readthedocs.io/en/2.2.0.post1/Installation.html#installation-methods):
> In case the Fortran comiler isn’t found, try `make FC=<path-to-gfortran> smodels` or `make FC=<path-to-gfortran> externaltools`.

This works for Pythia 6 but does not work for NLL-fast because the latter is compiled with `FCC`:

https://github.com/SModelS/smodels/blob/ce58a1f6647798267271bca7c7cd05aac4ae6298/smodels/lib/nllfast/nllfast-1.2/Makefile#L1-L7

https://github.com/SModelS/smodels/blob/ce58a1f6647798267271bca7c7cd05aac4ae6298/smodels/lib/nllfast/nllfast-2.1/Makefile#L1-L7

https://github.com/SModelS/smodels/blob/ce58a1f6647798267271bca7c7cd05aac4ae6298/smodels/lib/nllfast/nllfast-3.1/Makefile#L1-L7

A trivial workaround is to specify both:
```bash
make FC=/path/to/fortran FCC=/path/to/fortran externaltools
```
but it would be nice to unify the use of only `FC` or `FCC` if there is no particular reason.

**Comment by WolfgangWaltenberger** [comment]
Thanks, fixed it now (and adapted the docs) in the develop branch, which should be released soon. Will use FCC only.
