### ISSUE TITLE
passing TIMEOUT argument while calling SModelS from python

### ISSUE THREAD

**Issue by wkotlarski** [SModelS/smodels#35]
Dear Authors,

The command line interface has a `TIMEOUT` argument. Is there a way to achieve the same behavior when calling `SModelS` from python? My call routines are basically a copy of what is given in `Example.py`. There doesn't seem to be a place to pass `TIMEOUT`  there.

Best,
Wojciech

**Comment by WolfgangWaltenberger** [comment]
Hey Wojciech,

yes, in principle the following snippet should do the trick:
...
from smodels.tools import crashReport, timeOut
...
    try:
        with timeOut.Timeout(timeout):
            <do whatever you wish to see being done>
    except Exception as e:
        crashReportFacility = crashReport.CrashReport()

Hope it helps. Cheers

Wolfgang

**Comment by wkotlarski** [comment]
Hi Wolfgang. That solves my problem. Thanks for the tip.

Best,
Wojciech
