### ISSUE TITLE
Implementation on HPC (probably with NFS)

### ISSUE THREAD

**Issue by rahulgpuri** [SModelS/smodels#37]
fcntl.lockf ( dump, fcntl.LOCK_EX )
OSError: [Errno 38] Function not implemented

used in smodels/experiment/databaseObj.py

This error occurs when I try to run SModelS on a High-performance computing facility (HPC). A little research suggested that certain filesystems, such as NFS, do not allow its implementation.

**Comment by WolfgangWaltenberger** [comment]
Nice catch, thanks, will fix it in the next release. The lock is a protection against parallel downloads of the smodels database. So, interim, you should be fine with just commenting it out.

**Comment by rahulgpuri** [comment]
Thank you for getting back to me. I will try commenting it.

**Comment by WolfgangWaltenberger** [comment]
for the records I fixed it for v3 -- not for v2 -- in locking, merged into develop. will close because fixed
