### ISSUE TITLE
Deprication of 'imp' module starting from python 3.12

### ISSUE THREAD

**Issue by rahulgpuri** [SModelS/smodels#39]
The file _smodels/tools/modelTester.py_ uses '**imp**' module, which is deprecated starting from Python 3.12. I downgraded Python to Python 3.11.7 and got the following warning.
**DeprecationWarning**: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses

**Comment by WolfgangWaltenberger** [comment]
thanks, will change. meanwhile, just replace 'imp' with 'importlib', that should fix the issue.
Wolfgang
