### ISSUE TITLE
git lfs  for tarballs [smodels-utils]

### ISSUE THREAD

**Issue by andlessa** [SModelS/smodels#4]
This is for smodels-utils only. The tarballs currently stored in the HEPHY server should
be moved back to the slha folder in smodels-utils. Probably we will have to use git lfs,
since the files are quite large. Can we use a private server for it?

**Comment by WolfgangWaltenberger** [comment]
Using gzip, it seems this issue is not relevant anymore. Can we close it?

**Comment by andlessa** [comment]
Using gzip instead.
